//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pruebaEntities : DbContext
    {
        public pruebaEntities()
            : base("name=pruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual ObjectResult<CrearUsuario_Result> SP_Crear_Usuario(string usuario_red)
        {
            var usuario_redParameter = usuario_red != null ?
                new ObjectParameter("usuario_red", usuario_red) :
                new ObjectParameter("usuario_red", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CrearUsuario_Result>("SP_Crear_Usuario", usuario_redParameter);
        }
    
        public virtual ObjectResult<ConsultarUsuario_Result> SP_Consultar_Usuario(string criterio)
        {
            var criterioParameter = criterio != null ?
                new ObjectParameter("criterio", criterio) :
                new ObjectParameter("criterio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarUsuario_Result>("SP_Consultar_Usuario", criterioParameter);
        }
    
        public virtual ObjectResult<DesactivarUsuario_Result> SP_Desactivar_Usuario(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DesactivarUsuario_Result>("SP_Desactivar_Usuario", iDParameter);
        }
    
        public virtual ObjectResult<ModificarUsuario_Result> SP_Modificar_Usuario(Nullable<int> id_usuario, string usuario_red, string estado)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var usuario_redParameter = usuario_red != null ?
                new ObjectParameter("usuario_red", usuario_red) :
                new ObjectParameter("usuario_red", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ModificarUsuario_Result>("SP_Modificar_Usuario", id_usuarioParameter, usuario_redParameter, estadoParameter);
        }
    }
}
